### ISSUE TITLE
Error: Cannot find module '../metalsmith.json'

### ISSUE THREAD

**Issue by xlogan** [hariadi/generator-metalsmith#5]
I've just got the issue with the generator. Here is the full stack.

<pre>
module.js:340
    throw err;
    ^
Error: Cannot find module '../metalsmith.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at yeoman.generators.Base.extend.init (/Users/thopham/.nvm/v0.10.26/lib/node_modules/generator-metalsmith/app/index.js:19:23)
    at /Users/thopham/.nvm/v0.10.26/lib/node_modules/generator-metalsmith/node_modules/yeoman-generator/lib/base.js:341:43
    at /Users/thopham/.nvm/v0.10.26/lib/node_modules/generator-metalsmith/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /Users/thopham/.nvm/v0.10.26/lib/node_modules/generator-metalsmith/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/Users/thopham/.nvm/v0.10.26/lib/node_modules/generator-metalsmith/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at async.eachSeries (/Users/thopham/.nvm/v0.10.26/lib/node_modules/generator-metalsmith/node_modules/yeoman-generator/node_modules/async/lib/async.js:150:9)
</pre>

I'm working with node v0.10.26, yeoman 1.1.2. Any help?

**Comment by hariadi** [comment]
I tried it out with a fresh `yo metalsmith` using `node v0.10.26`, `yo 1.1.2`, `generator-metalsmith v0.2.2` and couldn't produce the error. Travis build also looks fine.

What version of your generator-metalsmith?

**Comment by xlogan** [comment]
Its 0.2.2. So weird. Anything I can share more?

**Comment by hariadi** [comment]
Can you confirm there is a file `metalsmith.json` in your `/Users/thopham/.nvm/v0.10.26/lib/node_modules/generator-metalsmith/` directory?

**Comment by xlogan** [comment]
No, it does not exist.

**Comment by hariadi** [comment]
Can you update `npm update -g generator-metalsmith`?  and verify `metalsmith.json` exist in your `/Users/thopham/.nvm/v0.10.26/lib/node_modules/generator-metalsmith/` directory.

**Comment by xlogan** [comment]
I always install yeoman generator with -g. I've just tried v0.2.1 as well, but no luck.

**Comment by hariadi** [comment]
I just update metalsmith generator. Can you try update to latest one? Thanks.

**Comment by xlogan** [comment]
Nice. It works like a charm.

**Comment by hariadi** [comment]
Thanks @xlogan
